# Generated by Django 4.2.5 on 2023-11-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['-date_added'], 'verbose_name': 'ShippingAddress', 'verbose_name_plural': 'ShippingAddresses'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['name'], 'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
    ]
