# Generated by Django 4.2.7 on 2023-11-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fast_delivery',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
